### ISSUE TITLE
GitHub's "Restrict who can push to matching branches" prohibits merge

### ISSUE THREAD

**Issue by tdeekens** [chdsbd/kodiak#119]
Thanks again for the bot. As discussion on another issue here a new one.

This option in GitHub:

<img width="732" alt="61939823-6b327400-af94-11e9-831f-fba4d974f0a9" src="https://user-images.githubusercontent.com/1877073/61949050-de92b080-afa9-11e9-8163-524e2129f549.png">

Disallows the bot to merge a PR. We use the option on Open Source repos to restrict access. Is there a way to allow the bot to still perform those actions? Thanks!

**Comment by chdsbd** [comment]
Hmm, this is tricky. I haven’t used this branch protection feature before, but from the looks of it, I bet Github doesn’t allow bot users to be added there. Is that correct?

I’m not sure there is anything we can do to support this besides reporting the issue to Github.

Let me know if you’re able to add Kodiak there. If not, I’ll document this limitation in the Readme and add a status message warning of this limitation.

**Comment by tdeekens** [comment]
> Let me know if you’re able to add Kodiak there. If not, I’ll document this limitation in the Readme and add a status message warning of this limitation.


No sadly I can't cause Kodiak is not user nor in a group to my knowledge. At least I failed to find the bot there.

**Comment by chdsbd** [comment]
Hmm, that’s disappointing. I’ll document this limitation sometime today. 

Let me know if you figure out a workaround.

**Comment by tdeekens** [comment]
It sounds like a limitation to any bot though. I am not sure how other bots would get around this.

**Comment by ardeois** [comment]
I've worked with [bors](https://github.com/bors-ng/bors-ng) in the past, and they handle that through github status checks.

Instead of sending a "neutral" status (like Kodiak does right now), Bors sends a "pending" status by default. When the PR is ready to merge it sends a "success" status then merges the PR.

If you update your branch settings so it requires "bors" status to be green before merging, only your bot will be able to merge PRs. Well except if a user is fast enough to click on merge between the time the bot pushes the status and executes the merge command, but it's unlikely

**Comment by chdsbd** [comment]
GitHub support got back to me and apparently there is an experimental feature they can enable for an organization/user account to allow Github Apps to be added in the "Restrict who can push to matching branches" branch protection setting.

So if you need this, I would contact support and ask them to enable it.

**Comment by tdeekens** [comment]
If they are working on this I think we can close this issue.
