### ISSUE TITLE
PR doesnt get merged

### ISSUE THREAD

**Issue by staabm** [chdsbd/kodiak#163]
sometimes a PR doesnt get merged by kodiak. in this cases kodiak states that it is waiting for 'travis ci' to get green.

but the ci checks already returned green.

this happened e.g. in the following PRs:
https://github.com/redaxo/redaxo/pull/2818
https://github.com/redaxo/redaxo/pull/2856

it works in 95% of our PRs as intended but sometimes doesnt... we werent able to identify why yet

see where all checks are already green but kodiak is still waiting for travis-ci:
![grafik](https://user-images.githubusercontent.com/120441/63416613-0980f080-c400-11e9-81c2-f4b1bce6d945.png)

we merged the PRs manually after waiting ~30min.

**Comment by chdsbd** [comment]
I see the issue. Github branch protection rules compact for `continuous-integration/travis-ci/{pr,pull,build,etc}` into `continuous-integration/travis-ci`. This only happens for `continuous-integration/travis-ci` as far as I can tell.

The fix is pretty straight forward. Thanks for reporting this.

**Comment by chdsbd** [comment]
I've opened an issue with GitHub because I think there is some undocumented behavior here on GitHub's side. I have a test case in #166 based on some experimentation with the GitHub api.

It appears that this only affects travis-ci and certain travis-ci checks.


Here are some examples of status check truncation behavior
```
continuous-integration/travis-ci/push => continuous-integration/travis-ci
continuous-integration/travis-ci/pr => continuous-integration/travis-ci
continuous-integration/travis-ci/deploy => continuous-integration/travis-ci/deploy

continuous-integration/example-ci/push => continuous-integration/example-ci/push
continuous-integration/example-ci/pr => continuous-integration/example-ci/pr
```

I'm not sure of all the travis-ci checks that truncate, I only have `continuous-integration/travis-ci/push` and `continuous-integration/travis-ci/pr` at the moment. Hopefully GitHub support will be able to provide more guidance on this odd behavior.

**Comment by chdsbd** [comment]
I think based on this issue [travis-ci#9618](https://github.com/travis-ci/travis-ci/issues/9618), if you want an immediate solution you could move to the newer Checks based api, which I believe won't have this problematic behavior.

**Comment by staabm** [comment]
Thx for the pointer. i just deleted the old services integrations. Lets see if this fixes the problem
