### ISSUE TITLE
Merge PRs that are ready first

### ISSUE THREAD

**Issue by lucleray** [chdsbd/kodiak#170]
Hi,

It happens that two PRs are ready to be merged (marked with the "automerge" label and approved for example). Then, they both go in the queue to be merged.

What happens in our repository sometimes is that the second PR that is "ready to be merged" pass all the tests faster than the first one. But since it is "2nd in the queue", it is slowed down by the other PR.

My suggestion for that would be to allow the bot to change the queue order, if one of the PR is the queue is ready before the others.

This could be an optimisation but also a great feature for some edge cases where some PRs are "stuck" because one of the check status is "blocked" as pending (it happens sometimes for us) and blocking the merging of PRs for the whole repository.

Thanks for your help 🙂

**Comment by chdsbd** [comment]
I think this should be possible. My first thought is that if a PR is 100% mergeable, instead of placing it in the queue, kodiak could just merge it in.

For the "stuck" issue, you may want to check out the `merge.dont_wait_on_status_checks` config option. It's useful for skipping status checks that haven't passed. I use it for the [WIP app](https://github.com/wip/app), which stays pending until WIP is removed from the title of a PR.

**Comment by chdsbd** [comment]
I’ll update this issue when #171 is deployed.

**Comment by chdsbd** [comment]
#171 has been deployed. Let me know if you have any problems.

**Comment by lucleray** [comment]
Thanks 😌
