### ISSUE TITLE
Kodiak status doesn't appear in PRs anymore

### ISSUE THREAD

**Issue by lucleray** [chdsbd/kodiak#189]
Since yesterday (25/11), Kodiak statuses doesn't appear anymore in our PRs. We didn't change the way it is configured. It seems to be down?

Thanks for your help!

**Comment by chdsbd** [comment]
Kodiak is working for me at work, so I'm not immediately sure what the issue is. I'm going to look through Sentry and the logs to see if I can find something.

Do you have a public repository where this is an issue?

**Comment by lucleray** [comment]
Thanks!

You can see it in this repo: https://github.com/zeit/docs. For example, this PR: https://github.com/zeit/docs/pull/1486.

**Comment by chdsbd** [comment]
I just restarted kodiak and that seems to have resolved the issue temporarily. I'll have time this evening to figure out a more permanent solution.

---

Here's what I found before I restarted the app.

https://github.com/zeit/now/pull/3346 was that last merged PR based on kodiak's redis instance.

GitHub was sending webhook events for zeit/docs, but it seems that the events weren't reaching this logic: https://github.com/chdsbd/kodiak/blob/158cda89378c8f8c850d8e88e31954823cef42ba/kodiak/queue.py#L103

**Comment by chdsbd** [comment]
The weird part is that this only affected a single installation, so I think it probably has something to do with per-installation logic like the rate limiting or per-install redis connection.
 
https://github.com/chdsbd/kodiak/blob/158cda89378c8f8c850d8e88e31954823cef42ba/kodiak/queue.py#L406-L408 
https://github.com/chdsbd/kodiak/blob/158cda89378c8f8c850d8e88e31954823cef42ba/kodiak/queue.py#L170-L184

Kodiak now runs on a normal VPS instead of Heroku where it would get cycled every night automatically, so maybe the issue was hidden before.

**Comment by lucleray** [comment]
Thanks! I'll let you know if it happens again 👍

**Comment by styfle** [comment]
Hi @chdsbd 

This seems to be happening again for the last 6 hours or so.

The Kodiak github status check is missing in our PRs.

**Comment by chdsbd** [comment]
Weird. I'll take a quick look.

**Comment by chdsbd** [comment]
@styfle What's your org name that you're using kodiak with?

**Comment by styfle** [comment]
Its the [ZEIT](http://github.com/zeit) org again, thanks!

**Comment by chdsbd** [comment]
I've restarted the machine and kodiak seems to be receiving events for zeit again.

**Comment by chdsbd** [comment]
Looks like it's working again based on this PR: https://github.com/zeit/docs/pull/1498
