### ISSUE TITLE
Clarification on repository content usage / data flows

### ISSUE THREAD

**Issue by ssengespeick** [chdsbd/kodiak#201]
Hi Christopher!

This is Sascha, a software developer from https://commercetools.com/.

We looked into automating our merging, decided on kodiak and - for the frontend - already use it. For the backend part, we have (and are met with) some reservations because it is not clear (not specified in the readme file) what data is actually read from the repository and if it's sent somewhere else.

While we can take a look into the code of the app (but would have to do this for every new version), our IT department is more interested in a statement by the developer(s) in some way. Either by updating the readme file or via email or some other written form.

Would you be open to specify what data is read by the app and transferred outside the app, specifically regarding the source code inside of the repository automated by the app?

Best,
Sascha Sengespeick

**Comment by chdsbd** [comment]
Hi Sascha,

Only application errors are sent externally to Sentry for error tracking. These messages would only include information necessary for Kodiak's operation, like PR status check info, Kodiak config, PR labels, PR title/body info. Additionally the Sentry account is only accessible by Kodiak’s maintainers (@chdsbd @sbdchd). Pull request numbers, as well as repo and org names are stored temporarily in Redis, which Kodiak uses as a message queue.

Kodiak accesses the `.kodiak.toml` file of a repository, but it does not access any other file in a repository or PR. Kodiak does not access any source code.

Kodiak does has access to every file in a repository because GitHub repository write permissions are required for Kodiak to update and merge branches.

Here's the queries that are run to fetch information for Kodiak's operation: https://github.com/chdsbd/kodiak/blob/master/kodiak/queries.py#L47-L163

Here’s documentation for Kodiak’s permissions: https://github.com/chdsbd/kodiak/blob/master/README.md#permissions

Hope this helps. Let me know if you have any more questions.

**Comment by chdsbd** [comment]
I've added some more privacy information in the docs: https://kodiakhq.com/docs/permissions

I'm going to close this issue, but let me know if you have any questions or concerns.

**Comment by ssengespeick** [comment]
Sorry for getting back to you so late.
Thanks a lot for the provided details, it helps us going forward!
