### ISSUE TITLE
merge.message.body: Only Co-Authors

### ISSUE THREAD

**Issue by gharlan** [chdsbd/kodiak#277]
When using "squash and merge" manually, github suggests a commit body containing the list of commits and the Co-Authors.

I don't want to get the commit list, but I would like to have the Co-Authors.
So I would like to have another option for `merge.message.body` like `co_authors`.
(But I don't know, if it is possible to implement this..)

**Comment by chdsbd** [comment]
I think this requires parsing the `Co-Authored-By` lines from the commit messages of a PR.

`Co-Authored-By: Jane Doe <jane.doe@users.noreply.github.com>`

This is possible. I think there could be an edge case where a PR has a lot of commits and Kodiak would probably not be able to quickly fetch all of those from the GitHub API, but I think it's okay if we ignore that.

For the implementation I think we'd make an API request here before generating the merge body.

https://github.com/chdsbd/kodiak/blob/9d98de1d694d21053abd6af81792cc6f04aa622a/kodiak/evaluation.py#L624-L628

**Comment by gharlan** [comment]
> I think this requires parsing the `Co-Authored-By` lines from the commit messages of a PR.

.. and collecting the authors from commits not authored by the pr author.

**Comment by chdsbd** [comment]
This change has been deployed to production.

This configuration option is undocumented at the moment. I'll fix that soon.

You must have these configuration options set for this feature to work.


```toml
merge.method = "squash"
merge.message.include_coauthors = true
merge.message.body = "pull_request_body"
```

I made `merge.message.include_coauthors` only apply to "squash" commits because I think "merge" commits should not have multiple authors. I'm open to changing this if someone else feels differently. ("rebase" doesn't create new commits so it's not relevant.)

You must set `merge.message.body = "pull_request_body"` for this feature to work. `"github_default"` uses the GitHub autogenerated message that we cannot modify. I figure `"empty"` should always leave the merge commit empty.

**Comment by gharlan** [comment]
> I figure `"empty"` should always leave the merge commit empty.

I don't agree here. In our project the pr description is often outdated, when finally merging the pr. That is the reason why I don't want to include the description in the final commit. But I still would like to get the co authors.

**Comment by chdsbd** [comment]
Yeah, that sounds good to me. Thanks for the feedback.

I think it's a one line change to remove the check on `merge.message.body`:

https://github.com/chdsbd/kodiak/blob/da1e1bfaa0b4909fa9f3ee4fe996436233c5234f/bot/kodiak/evaluation.py#L194-L197

**Comment by chdsbd** [comment]
@gharlan #561 is now deployed so `include_coauthors` should now work with `body = "empty"`.
