### ISSUE TITLE
How to configure Kodiak wait for Github Actions to pass before merge?

### ISSUE THREAD

**Issue by TomasVotruba** [chdsbd/kodiak#341]
This is my config: https://github.com/symplify/symplify/blob/master/.kodiak.toml

I have this pull-request: https://github.com/symplify/symplify/pull/1857

And the pull-request branch is protected:

![image](https://user-images.githubusercontent.com/924196/79772348-46efa200-8330-11ea-828d-a737b77114a5.png)

Yet the PR get merged **before** the CI passes, right after I add the label `autormerge`. 

How can I fix it to merge it only afte rthe CI passes?

**Comment by chdsbd** [comment]
Hi @TomasVotruba,

GitHub branch protection will block Kodiak from merging a PR until required status checks pass, so I think this is probably a misconfiguration of the branch protection settings.

Does your branch protection target the correct branch?

Mine looks like the following:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/1929960/79778386-a769e980-8306-11ea-987a-6bfd8e4b05ff.png">

Also, are all of your CI checks enabled in the list?

This is what mine looks like:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/1929960/79778477-c8323f00-8306-11ea-8eb6-81756cbcea5a.png">

This may be because I'm not a member of your organization, but I noticed your CI checks don't have a "REQUIRED" badge next to them.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/1929960/79778951-8bb31300-8307-11ea-9073-2091487e12d3.png">

For Kodiak's repository, they look like the following:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/1929960/79779057-b604d080-8307-11ea-8370-4c52c73c7843.png">

Hope this helps.

Let me know if you have any more questions.

**Comment by TomasVotruba** [comment]
Ah, I thought it should target the pull-request **from** branch. Not the target one... I'll try :+1:  thanks

**Comment by TomasVotruba** [comment]
Works great now, thanks!

**Comment by chdsbd** [comment]
Great to hear. Thanks for the sponsorship as well. 😊
