### ISSUE TITLE
Not merging Pull Request when self-hosted

### ISSUE THREAD

**Issue by MaicolBen** [chdsbd/kodiak#400]
I had a lot of PRs with different messages that says something but it isn't merging, they are:
<img width="589" alt="Screen Shot 2020-05-21 at 18 55 10" src="https://user-images.githubusercontent.com/3474627/82611461-f66d9d80-9b96-11ea-9121-11b70763ccd5.png">
But it is the only one PR, it was like that for an hour

<img width="370" alt="Screen Shot 2020-05-21 at 19 11 07" src="https://user-images.githubusercontent.com/3474627/82611485-01283280-9b97-11ea-913b-6f66476f1dec.png">

But all the checks are green

Thank you!

**Comment by chdsbd** [comment]
Are you sure that the codeclimate status check has succeeded?

Can you try editing that PR (changing the title, labels, etc.) and seeing if that triggers Kodiak to merge the PR? Also, do you have a log output from Kodiak available?

The reason you see the `enqueued for merge (position={1st,2nd,3rd})` is because Kodiak tries to be efficient when merging and by default uses a merge queue so only one pull request is updated and merged at a time.

**Comment by MaicolBen** [comment]
> The reason you see the

I know because when it wasn't self-hosted, it was working like a charm. I will attach you some proofs (now not even shows up in the PR):
![Screen Shot 2020-05-25 at 11 25 50](https://user-images.githubusercontent.com/3474627/82822514-5062b180-9e7c-11ea-9e93-3973a2483cc3.png)
![Screen Shot 2020-05-25 at 11 26 37](https://user-images.githubusercontent.com/3474627/82822522-52c50b80-9e7c-11ea-9bd6-e2a2a18e9816.png)

Heroku has this redis errors but I think is ok since I checked redis itself and everything is ok
![Screen Shot 2020-05-25 at 11 27 09](https://user-images.githubusercontent.com/3474627/82822637-7be59c00-9e7c-11ea-98ed-ed794564213a.png)

**Comment by chdsbd** [comment]
That Heroku error looks like a problem to me. `asyncio_redis` is the library Kodiak uses to connect to Redis, so I think hitting connection errors like that is probably an issue.

Can you try restarting Kodiak and providing any logs in a Gist?

**Comment by chdsbd** [comment]
Also, I recently updated the docs to include a couple forgotten webhook event subscriptions: `push` and `status`.

https://kodiakhq.com/docs/self-hosting

**Comment by MaicolBen** [comment]
Thank you, I added those events. Here it's the full logs https://gist.github.com/MaicolBen/b7e4093994cc37a290c20aab147c9eae

**Comment by chdsbd** [comment]
It seems the Redis instance is running out of connections. https://gist.github.com/MaicolBen/b7e4093994cc37a290c20aab147c9eae#file-kodiak_logs-txt-L62

Kodiak opens a connection pool on start and the default size should be pretty small by default https://github.com/chdsbd/kodiak/blob/master/bot/kodiak/app_config.py#L15.

I think it takes time for the connection usage information to be updated in Heroku, so you might have luck turning off the dyno, waiting a bit and then turning it on again. Otherwise you probably need to upgrade your Redis instance to support more connections.

**Comment by MaicolBen** [comment]
Yeah, I just upgraded and it worked correctly! Thank you very much!
