### ISSUE TITLE
Interaction with dependabot when there's a merge conflict

### ISSUE THREAD

**Issue by infokiller** [chdsbd/kodiak#492]
Hi,
I configured kodiak with dependabot as [documented](https://github.com/infokiller/selfspy/pull/56). One issue I encountered in [a PR of one of my forks](https://github.com/infokiller/selfspy/pull/56) is that kodiak removes the `automerge` label when it encounters a merge conflict. However, dependabot didn't add that label back after it resolved the conflict, which requires me to do the merge manually.
This situation is quite common with dependabot, since it sends multiple PRs when multiple deps have new versions. After merging the first of these PRs, a merge conflict usually happens because all the PRs target the same file (`requirements.txt`, etc).

Am I doing something wrong?
Thanks!

**Comment by chdsbd** [comment]
Thanks for the report.

Removing the "automerge" label is expected behavior in general, but thinking about it more I realize it's probably not the best user experience.

As a workaround you can disable Kodiak leaving a comment on merge conflicts by setting: https://kodiakhq.com/docs/config-reference#mergenotify_on_conflict. This will stop Kodiak from removing the "automerge" label.


```toml
merge.notify_on_conflict = false
```
