### ISSUE TITLE
Branch updated multiple times

### ISSUE THREAD

**Issue by sindrig** [chdsbd/kodiak#515]
So far we're really loving kodiak!

Is there a way to limit the number of update merge commits to PRs? E.g. only to update the branch when all checks (actions and reviews) are done and the PR is eligible for merge?

PR in question: https://github.com/island-is/island.is/pull/1078 where kodiak updated the branch 4 times.

**Comment by sindrig** [comment]
After reading through the discussions on https://github.com/chdsbd/kodiak/issues/87 I guess this is related? Especially https://github.com/chdsbd/kodiak/issues/87#issuecomment-515784006. LMK and then we can close this as duplicate.

**Comment by chdsbd** [comment]
Hi @sindrig,
You're correct. This issue is related to code owners. I recently learned of a new GraphQL field called `reviewDecision` that I'm hoping to use in #509 to resolve this issue. Sadly this new field seems to be broken when "Require review from Code Owners" is enabled. I'm communicating with GitHub support to hopefully resolve this bug soon (within the week).

**Comment by sindrig** [comment]
Thanks for the quick reply. If you need any help resolving this feel free to reach out!
