### ISSUE TITLE
the bot sends merging message ever and again.

### ISSUE THREAD

**Issue by portlek** [chdsbd/kodiak#599]
![image](https://user-images.githubusercontent.com/12835420/102698416-1741c280-424e-11eb-937e-b667a6fa332f.png)
![image](https://user-images.githubusercontent.com/12835420/102698419-1ad54980-424e-11eb-8b0c-68a158322181.png)
idk why

**Comment by chdsbd** [comment]
Kodiak evaluates a PR for merging whenever the PR is modified (commits added, labels edited, description modified, etc.). Kodiak then updates the status message based on that evaluation. So for every modification to a PR, Kodiak will set the status message.

When Kodiak attempts to merge a PR, Kodiak enters a loop where it evaluates a PR for mergeability. On each evaluation the status message is updated.

If we only wanted to set a status message when the message has change, we'd need to store the status messages for every PR and then check before calling the GitHub API.

I'd try changing your Discord/GitHub integration to see if it can report only failing status checks. Kodiak sets a neutral status check.

**Comment by chdsbd** [comment]
I think best case we could make Kodiak only update its status when the text has changed. But even still, if Kodiak was waiting for 10 status checks, it could update ~10 times. This would still leave a lot of updates to your channel.

I'm going to close this because I don't think there's a solution here and I don't feel like this is a bug with Kodiak.
