### ISSUE TITLE
Merge queues UI not working

### ISSUE THREAD

**Issue by scriptnull** [chdsbd/kodiak#623]
I notice that one of the PRs in our repo show up

![image](https://user-images.githubusercontent.com/4211715/110578494-f755d700-818a-11eb-9959-0bc194a1bd26.png)

But when I login to kodiak dashboard, the UI still show this:

![image](https://user-images.githubusercontent.com/4211715/110578529-0c326a80-818b-11eb-80de-a7e5e69840c0.png)

any idea?

**Comment by chdsbd** [comment]
I would try editing that pull request so Kodiak re-evaluates it: https://kodiakhq.com/docs/troubleshooting#workarounds

I'm not sure why Kodiak stopped working on that PR.

**Comment by chdsbd** [comment]
It turns out my implementation for displaying the merge queues in the web UI was flawed.

For Redis' `SCAN` command, the `MATCH` argument matches _after_ returning a page of results. So using `SCAN` isn't guaranteed to find all the matching queues.

I think this is why the dashboard is showing "No active merge queues to display" for you. I also encountered the same issue.

https://github.com/chdsbd/kodiak/blob/b8527c1e7ab9668c2f4e0230a00fd250e61f8bac/web_api/web_api/merge_queues.py#L58

I'm working on a fix that will make merge queues reliably display in the dashboard.

**Comment by chdsbd** [comment]
This should be fixed now that #632 is deployed. Let me know if you have any issues.

Here's what the view looks like now for my Kodiak test repo, "test_repo_prod"
<img width="508" alt="Screen Shot 2021-03-21 at 7 58 10 PM" src="https://user-images.githubusercontent.com/1929960/111925584-e016c380-8a7f-11eb-8f2e-dc3206d62657.png">

**Comment by scriptnull** [comment]
Thanks for the fix @chdsbd :+1: Works like a charm this time :ok_hand:
