### ISSUE TITLE
Support for autoupdating but not merging

### ISSUE THREAD

**Issue by AnthonyReid99** [chdsbd/kodiak#75]
Would it be possible to allow auto-updating on a branch but NOT auto-merging?

Absence of this feature is UNACCEPTABLE!!!! 🛑😡😢

Thanks :)

**Comment by chdsbd** [comment]
Lol. I wasn't watching this repo on Github so I didn't see this until now.

I'm curious why you would want to update a branch without merging. I think there may be a different feature that could be added to better support that use case. Do you want to define the commit messages yourself or is it something else?

I'm not sure kodiak would be useful if it only updated branches and didn't merge them.

Right now kodiak has a merge queue that ensures we apply the minimal number of updates to PRs before they are merged into their target branch. If we only updated a PR I'm not sure how we would keep this. I think we would basically just need to update every PR whenever the target branch was updated, which would add a bunch of useless merge commits and start a bunch of useless CI jobs.

Let me know what you think.

**Comment by AnthonyReid99** [comment]
Perhaps I've misunderstood how github handles updating branches, I'm basically looking for something that rebases my branch on master whenever master updates (if it's possible, and maybe alert me if not possible due to merge conflict). If GH creates merge commits for these, then I can see your point about creating unnecessary commits. 

Perhaps Kodiak is not the bear for me?

**Comment by chdsbd** [comment]
It's certainly possible to update your branch when the target (e.g. master) updates, and that's what some projects listed in the [prior art section](https://github.com/chdsbd/kodiak#prior-art) like [bulldozer](https://github.com/palantir/bulldozer) do, but it's inefficient.

Automatically updating every PR whenever the target changes is wasteful because only one of those PRs will be merged if we enforce that all PRs must be up to date before merging.

Kodiak is smart in that it only will your branch if needed before it merges into the target, so you never need to push the "Update Branch" button.

 Does that answer your question?

**Comment by AnthonyReid99** [comment]
Yeah, that makes sense. The reason I rebase my branch whenever I notice it's out of date is just to stay on top of potential merge conflicts. But I do see how that could be wasteful

**Comment by chdsbd** [comment]
If you get a merge conflict kodiak will leave a comment on your PR which should give you a notification through Github.

**Comment by alex-sf** [comment]
We are trying to accomplish autoupdating without merging. The reason we need this is because Kodiak does not support signed commits so we would like it to keep our PR branches up to date but the final squash commit needs to come from a non-bot. 

I would like to take advantage of the Kodiak's smart updating to do something like the following:

* Check to see if it is ok to merge (ie tests pass, approvals are given, etc)
* update the branch 
* don't merge 

Is this possible?

**Comment by chdsbd** [comment]
I'm afraid Kodiak doesn't seem to support this use case.

You might be able to find a solution in the alternatives section of the [README](https://github.com/chdsbd/kodiak#prior-art--alternatives), but I'm not sure any of those will do smart updates.

I think a new configuration option could be added to Kodiak to support this behavior, but I can't commit to a timeline on adding it.

**Comment by alex-sf** [comment]
@chdsbd I was looking at the code it I think I have a pretty simple solution to this https://github.com/chdsbd/kodiak/pull/187. Let me know if there is anything that needs to be added or if my logic is incorrect, since you have a much better holistic view of the entire repo.

**Comment by chdsbd** [comment]
Fixed via #187
