### ISSUE TITLE
Kodiak missing from checks 

### ISSUE THREAD

**Issue by styfle** [chdsbd/kodiak#874]
Kodiak is missing from the checks on this PR: https://github.com/vercel/vercel/pull/10133

Even though the automerge label is applied, it seems like it will never merge https://github.com/vercel/vercel/blob/main/.kodiak.toml#L4C1-L4C1

Is kodiak down right now?

<img width="458" height="301" alt="screenshot" src="https://github.com/chdsbd/kodiak/assets/229881/1dd63838-c933-41a4-a245-f3c6092c119c">

**Comment by chdsbd** [comment]
I've been looking at this for a while and I think the issue is the number of web hook events in the installation's queue.

Kodiak has a single queue per installation to process all web hooks. Whenever a PR is merged, Kodiak enqueues all open PRs ([up to 100 per repo](https://github.com/chdsbd/kodiak/blob/d6f1720f7ad7babb2f25283d9bf51c3f7e031a44/bot/kodiak/queries/__init__.py#L1151-L1152)) to recheck merge status. So if you have repos with a large number of open PRs, there's going to be a large number of PRs added to the queue.

There's currently 321 PRs in the queue for evaluation, so Kodiak will take some time to evaluate those based on GitHub API rate limits.

I wonder if we can filter out PRs more here or increase concurrency: https://github.com/chdsbd/kodiak/blob/d6f1720f7ad7babb2f25283d9bf51c3f7e031a44/bot/kodiak/queue.py#L214-L215

**Comment by chdsbd** [comment]
I think the move going forward is to update Kodiak to have more tasks working on the web hook queue. If we have rate limit issues, we can figure something else out

**Comment by styfle** [comment]
> So if you have repos with a large number of open PRs, there's going to be a large number of PRs added to the queue.

Is it repo or org? Because the repo only has 56 open PRs which doesn't sound like a lot to me.

https://github.com/vercel/vercel/pulls?q=is%3Apr+is%3Aopen

**Comment by styfle** [comment]
I tested it and confirmed that all 56 return in a single api response:

```
curl -sSL 'https://api.github.com/repos/vercel/vercel/pulls?per_page=100' | jq '. | length'
```

**Comment by chdsbd** [comment]
It’s per organization, so it can add up across repos

**Comment by styfle** [comment]
Since PRs are technically Issues, you could change the API call to Issue and filter by the merge label.

For example, this returns the 1 open PR that has the `pr: automerge` label: 

https://api.github.com/repos/vercel/vercel/issues?per_page=100&labels=pr%3A+automerge

Now that only works when the repo is configured to include the [`automerge_label`](https://github.com/vercel/vercel/blob/main/.kodiak.toml#L4C1-L4C1) but that could reduce the number in the queue quite a bit.

**Comment by chdsbd** [comment]
My plan is to increase the concurrency for web hook ingestion

**Comment by chdsbd** [comment]
I've deployed a change to increase the concurrency for your organization to 5 ingest workers. I'm going to monitor the GitHub API rate limits and increase the worker count if the rate limiting isn't an issue

**Comment by chdsbd** [comment]
I realized yesterday that Kodiak throttles [API requests to 5000/hour by default](https://github.com/chdsbd/kodiak/blob/a16e7bad659a3f48ac39038f9337a4f178e46c8f/bot/kodiak/throttle.py#L69-L73). Since your organization is on GitHub Enterprise, Kodiak has a 15,000/hour rate limit.

I've deployed a change that enables your organization to utilize the 15k rate limit

**Comment by styfle** [comment]
Re-opening since the problem is happening again now.

Kodiak shows nothing in the queue but there is [a PR](https://github.com/vercel/next.js/pull/51733) that says its 3rd in the queue for about 12 minutes now.

<img width="711" alt="image" src="https://github.com/chdsbd/kodiak/assets/229881/16985853-af9b-4bc9-885d-e2946be73851">

<img width="845" alt="image" src="https://github.com/chdsbd/kodiak/assets/229881/47100b4e-0ece-4507-bad8-c77868ff36f0">

**Comment by chdsbd** [comment]
It might be the rate limit, the logging on rate limits is lacking, so I'll turn down the internal Kodiak limit for now

**Comment by chdsbd** [comment]
I added some better logging, it seems like we're hitting a different rate limit.


I'm seeing errors for GraphQL queries (`https://api.github.com/graphql`) and check-runs `https://api.github.com/repos/vercel/api/check-runs`

```
{
  "documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."
}
```

**Comment by chdsbd** [comment]
I think we can update our throttling logic to wait for the "retry-after" time when we hit a secondary rate limit

**Comment by styfle** [comment]
Why 60 seconds? The linked docs say 1 second.

> If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, wait at least one second between each request.

**Comment by styfle** [comment]
I suppose if the rate limit is hit, then yes it will have to wait for the duration of `Retry-After`.

But maybe setting a delay of 1 sec between requests will ensure the rate limit is never hit?

**Comment by styfle** [comment]
This one has been ready to merge for about 45 min https://github.com/vercel/vercel/pull/10164

**Comment by chdsbd** [comment]
Thanks for the ping here. I think I need to synchronize the graphql calls so we only make one per installation at a time. It seems like the REST API isn't returning the secondary rate limit errors.

I triggered a refresh of that pull request and it merged (you can do this by editing the pull request title, description, labels, or commits).

Kodiak wasn't actively looking at this PR, I think Kodiak hit the secondary rate limit and dropped the event, because we don't retry on those errors.

My TODOs are:

- [ ] add some sort of lock so we only make one concurrent graphql request per installation
- [ ] when we hit a secondary rate limit, enqueue the pull request again for evaluation instead of dropping it

**Comment by styfle** [comment]
Now I'm seeing a new error message. Perhaps GitHub's API is down?

<img width="940" alt="image" src="https://github.com/chdsbd/kodiak/assets/229881/d2d1b9c0-2637-4f3b-97bb-94a0721d5cfc">

**Comment by chdsbd** [comment]
I think that's because of the secondary rate limit, I'm going to try to temporarily reduce the graphql requests by limiting the ingest workers to 1

**Comment by chdsbd** [comment]
Hey @styfle,

Sorry for the delayed reply. Last week after my message above I made a change to requeue pull requests on api rate limits, which I think ensures we no longer drop pull requests for these limits

I’ll take a look at the PR you linked

**Comment by chdsbd** [comment]
This error is unrelated to this original issue

https://github.com/vercel/next.js/runs/14992559502

Here’s the issue for this error: https://github.com/chdsbd/kodiak/issues/853

I talked to GitHub a while back and the product team there said this was expected behavior

**Comment by styfle** [comment]
Is this the same bug? 

> kodiakhq: status — ⚠️ problem contacting GitHub API with method 'pull_request/merge'

<img width="868" alt="image" src="https://github.com/chdsbd/kodiak/assets/229881/015549b2-bbba-45c6-b7f8-9e5eeac200d3">

https://github.com/vercel/next.js/pull/53520

**Comment by styfle** [comment]
Closing since it seems the remaining issues we've had are the same as https://github.com/chdsbd/kodiak/issues/853
