### ISSUE TITLE
"could not determine why PR is blocked" error

### ISSUE THREAD

**Issue by rgeraldporter** [chdsbd/kodiak#98]
<img width="763" alt="Screen Shot 2019-07-25 at 11 50 56" src="https://user-images.githubusercontent.com/955052/61888949-89d03680-aed2-11e9-9388-0f114ad42964.png">

Hi folks, currently seeing this in a (private) repo where I'm testing kodiak out. Is there some way I can find out more about why it's blocked from merging? It currently has the two requisite reviews it requires for merging, and other statuses are passed.

**Comment by chdsbd** [comment]
@rgeraldporter Do you have CODEOWNERS enabled? It may be related to #87. If not, can you send a screenshot of your branch protection settings?

This error occurs when Github says a PR is blocked, but kodiak doesn't know the reason, likely because we don't handle some branch protection setting.

Here's the code: https://github.com/chdsbd/kodiak/blob/master/kodiak/evaluation.py#L262

If you meet all your branch protection requirements kodiak should remove this message and merge the PR, it's just that from the current PR state kodiak doesn't know the requirements you need to meet.

**Comment by rgeraldporter** [comment]
Ah, yes, when I removed the code owners stuff, it merged fine. I'm guessing that's something you're working on from what I see in other discussions?

**Comment by chdsbd** [comment]
Yeah. Hopefully it will be done by tomorrow.

**Comment by rgeraldporter** [comment]
thanks! Looking forward to it.

**Comment by tdeekens** [comment]
Thanks for the discussion here. I am seeing the same "issue" and am not using code owners. I am wodnering if this setting also prevents the bot to merge. If so how could I work around it: 

<img width="732" alt="CleanShot 2019-07-26 at 10 58 57@2x" src="https://user-images.githubusercontent.com/1877073/61939823-6b327400-af94-11e9-831f-fba4d974f0a9.png">

**Comment by chdsbd** [comment]
@tdeekens Can you open a new issue? I think the issue you've encountered is different.
